### ISSUE TITLE
Running `rails db:prepare` creates a development database with test environment set

### ISSUE THREAD

**Issue by aramvisser** [oldmoe/litestack#46]
Usually running `rails db:create` creates both the development and test database. However, with litestack installed, only the development database is created in `db/development`, but no test database is created in `db/test`.

Manually setting a database path inside `config/database.yml` for the test database fixes this issue:

```yaml
default: &default
  adapter: litedb
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  idle_timeout: 0
  database: <%= Litesupport.root.join("data.sqlite3") %>

development:
  <<: *default

test:
  <<: *default
  database: ./db/test/data.sqlite3 # Manually set path here
```

I assume the reason is that when the test database is created during `rails db:create`, the `Litesupport.root` path doesn't get updated and still uses the development path.

### Steps to reproduce

```
> rails new litestackapp
> cd litestackapp
> bundle add litestack
> rails generate litestack:install
> rails db:prepare
> sqlite3 db/development/data.sqlite3 "select * from ar_internal_metadata"
```

### Expected behavior

There should be a row with development environment

> environment|development|2023-10-16 07:14:34.551049|2023-10-16 07:14:34.572026

### Actual behavior

The environment is set to test instead:

> environment|test|2023-10-16 07:14:34.551049|2023-10-16 07:14:34.572026

### System configuration

Rails 7.1.1
Litestack 0.4.1 and master branch
